void glAttachShader(void){}
void glBindAttribLocation(void){}
void glBindBuffer(void){}
void glBlendFunc(void){}
void glBufferData(void){}
void glClear(void){}
void glClearColor(void){}
void glCompileShader(void){}
void glCreateProgram(void){}
void glCreateShader(void){}
void glDrawArrays(void){}
void glEnable(void){}
void glEnableVertexAttribArray(void){}
void glGenBuffers(void){}
void glGetProgramiv(void){}
void glGetShaderInfoLog(void){}
void glGetShaderiv(void){}
void glGetString(void){}
void glGetUniformLocation(void){}
void glLinkProgram(void){}
void glShaderSource(void){}
void glUniform1f(void){}
void glUniform2f(void){}
void glUniform4f(void){}
void glUniform4fv(void){}
void glUseProgram(void){}
void glVertexAttribPointer(void){}
void glViewport(void){}
void glGetIntegerv(void){}
void glGenTextures(void){}
void glBindTexture(void){}
void glTexImage2D(void){}
void glTexParameteri(void){}
void glActiveTexture(void){}
void glPixelStorei(void){}
void glDeleteTextures(void){}
void glUniform1i(void){}
