#!/usr/bin/env python3
"""Read saved ABR device logs and print the transaction/plant tables, as markdown.

WHY THIS IS A TOOL. The first draft of `docs/measurements/p1-transaction-anatomy.md` had five
wrong numbers in its headline table -- not misread, but transcribed from a log that a later run
of the same case had already overwritten. Numbers hand-copied out of a terminal into a document
cannot be re-checked without redoing the run, and a measurement nobody can re-derive is an
anecdote. Every table in that document is generated by this script, so re-running it against the
same logs reproduces it exactly, and running it against new logs says so.

    tools/abr-tx-report.py <log-dir-or-files>...
    tools/abr-tx-report.py /tmp/abr-p1-logs --section cost

Reads `abr: tx`, `abr: sample` and `hls: segment` through `tests/run.py`'s own regexes, so a
format change breaks this the same way it breaks the harness -- and is caught by the contract
test in `tests/test_harness.py` rather than by a silently empty table here.
"""
import argparse, glob, importlib.util, os, statistics, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tests"))
import run                                                        # noqa: E402


def load_sweep():
    """`tools/abr-plant-sweep.py` owns the queue geometry; this never re-derives it."""
    spec = importlib.util.spec_from_file_location(
        "sweep", os.path.join(ROOT, "tools", "abr-plant-sweep.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def collect(paths):
    logs = []
    for p in paths:
        logs += sorted(glob.glob(os.path.join(p, "*.log"))) if os.path.isdir(p) else [p]
    tx, samples = [], []
    for path in logs:
        lines = open(path, encoding="utf-8", errors="replace").read().splitlines()
        case = os.path.basename(path)[:-4]
        for r in run.abr_transactions(lines):
            r["_case"] = case
            tx.append(r)
        for s in run.abr_samples(lines):
            s["_case"] = case
            samples.append(s)
    return logs, tx, samples


def thousands(n):
    return f"{n:,}".replace(",", " ")


def section_cost(tx, **_):
    sel = sorted((r for r in tx if r["feed_ms"] is not None and r["decided_ms"] is not None),
                 key=lambda r: -r["feed_ms"])
    print("| move | decided | feed | what `decided` used to report | feed's share |")
    print("|---|---:|---:|---:|---:|")
    for r in sel:
        total = r["decided_ms"] + r["feed_ms"]
        share = 100 * r["feed_ms"] // total if total else 0
        b = "**" if r["feed_ms"] > 19_000 else ""
        print(f"| {r['from_kbps']} -> {r['to_kbps']} | {b}{thousands(r['decided_ms'])}{b} | "
              f"{b}{thousands(r['feed_ms'])}{b} | {thousands(total)} | {b}{share}%{b} |")
    dec = [r["decided_ms"] for r in tx if r["decided_ms"] is not None]
    fed = [r["feed_ms"] for r in tx if r["feed_ms"] is not None]
    med = lambda v: sorted(v)[len(v) // 2]
    print(f"\nn = {len(tx)} transactions. **`decided` median {thousands(med(dec))} ms, "
          f"max {thousands(max(dec))} ms.** "
          f"**`feed` median {thousands(med(fed))} ms, max {thousands(max(fed))} ms.**")


def section_drain(tx, sweep, **_):
    """Does the reserve fall at exactly real time while the feed is blocked?"""
    print("| move | feed_ms | reserve drained | ratio |")
    print("|---|---:|---:|---:|")
    ratios = []
    for r in sorted((x for x in tx if x["to_kbps"] > x["from_kbps"] and x["feed_ms"]
                     and x["feed_ms"] > 1000 and x["buf_fed_ms"] is not None),
                    key=lambda x: -x["feed_ms"]):
        n = 2 if r["graded_ms"] is not None else 1
        drained = r["buf_decided_ms"] + n * sweep.D_MS - r["buf_fed_ms"]
        ratio = drained / r["feed_ms"]
        ratios.append(ratio)
        b = "**" if abs(ratio - 1) < 0.02 else ""
        print(f"| {r['from_kbps']} -> {r['to_kbps']} | {thousands(r['feed_ms'])} | "
              f"{thousands(drained)} | {b}{ratio:.2f}{b} |")
    if ratios:
        print(f"\nn = {len(ratios)}, ratio {min(ratios):.2f} .. {max(ratios):.2f}. "
              "1.00 is conservation: the feed blocks while playback keeps consuming at 1x.")


def section_ceiling(tx, sweep, **_):
    slack, bound = [], []
    for r in tx:
        if r["buf_fed_ms"] is None or r["buf_decided_ms"] is None:
            continue
        n = 2 if r["graded_ms"] is not None else 1
        unclamped = r["buf_decided_ms"] + n * sweep.D_MS
        bmax = sweep.b_max_ms(r["to_kbps"], sweep.AQ_VIDEO_BYTES, sweep.AQ_AUDIO_BYTES,
                              sweep.FEED_AHEAD_MS, sweep.AUDIO_SLACK_MS)
        (bound if unclamped > bmax else slack).append(
            (r, r["buf_fed_ms"] - min(unclamped, bmax), bmax))
    print(f"* **Ceiling slack (n = {len(slack)}):** errors "
          f"{sorted(e for _, e, _ in slack)}")
    if bound:
        errs = [e for _, e, _ in bound]
        rel = [100.0 * e / b for _, e, b in bound]
        print(f"* **Ceiling binding (n = {len(bound)}):** {min(errs):+} ms to {max(errs):+} ms "
              f"({min(rel):+.1f}% to {max(rel):+.1f}%); "
              f"{sum(1 for e in errs if e < 0)} of {len(errs)} negative.")
    print("\n| move | feed_ms | buf_fed | B_max(new) | ratio |")
    print("|---|---:|---:|---:|---:|")
    for r, _, bmax in sorted(bound, key=lambda x: -(x[0]["feed_ms"] or 0)):
        if r["feed_ms"] is None or r["feed_ms"] < 1000:
            continue
        print(f"| {r['from_kbps']} -> {r['to_kbps']} | {thousands(r['feed_ms'])} | "
              f"{thousands(r['buf_fed_ms'])} | {thousands(bmax)} | "
              f"{r['buf_fed_ms'] / bmax:.2f}x |")


def section_control(tx, **_):
    med = lambda v: sorted(v)[len(v) // 2]
    for name in ("prime_ms", "master_ms", "media_ms", "control_ms"):
        v = [r[name] for r in tx if r[name] is not None]
        if v:
            print(f"* `{name[:-3]}`: median {med(v)} ms, {min(v)}-{max(v)} ms, n={len(v)}")


def section_rates(samples, sweep, **_):
    byrung = {}
    for s in samples:
        byrung.setdefault(s["current_kbps"], []).append(s["media_kbps"])
    print("| rung | n | median kbps | min | max | max/min |")
    print("|---:|---:|---:|---:|---:|---:|")
    for rung in sorted(byrung):
        v = byrung[rung]
        spread = max(v) / min(v) if min(v) else 0
        b = "**" if abs(spread - 1) < 1e-9 else ""
        print(f"| {rung} | {len(v)} | {thousands(int(statistics.median(v)))} | "
              f"{thousands(min(v))} | {thousands(max(v))} | {b}{spread:.2f}{b} |")
    ratios = [statistics.median(byrung[r]) / r for r in byrung]
    print(f"\nn = {len(samples)} samples over {len(byrung)} rungs. "
          f"delivered/requested {min(ratios):.2f}x .. {max(ratios):.2f}x "
          f"({max(ratios) / min(ratios):.1f}x span).")


SECTIONS = {"cost": section_cost, "drain": section_drain, "ceiling": section_ceiling,
            "control": section_control, "rates": section_rates}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("paths", nargs="+", help="log files or directories of *.log")
    ap.add_argument("--section", choices=sorted(SECTIONS), action="append",
                    help="only this section (repeatable); default is all")
    args = ap.parse_args(argv)

    sweep = load_sweep()
    logs, tx, samples = collect(args.paths)
    if not tx and not samples:
        print("no `abr: tx` or `abr: sample` lines found — wrong logs, or the format moved "
              "and tests/run.py's regexes no longer match it.", file=sys.stderr)
        return 1
    print(f"<!-- generated by tools/abr-tx-report.py from {len(logs)} log(s): "
          f"{', '.join(os.path.basename(p) for p in logs)} -->\n")
    for name in (args.section or sorted(SECTIONS)):
        print(f"### {name}\n")
        SECTIONS[name](tx=tx, samples=samples, sweep=sweep)
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
